name: Ahihi checker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build_Elements.CheckBox:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.6
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
    - run: nuget restore Re-Framework.sln
    - name: Restore dependencies
      run: dotnet restore
    - name: Build app for release
      run: msbuild Re-Framework.csproj
    - name: Test
      run: dotnet test --filter TestCategory="CheckBox tests"
      
  Build_Elements.TextBox:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.6
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
    - run: nuget restore Re-Framework.sln
    - name: Restore dependencies
      run: dotnet restore
    - name: Build app for release
      run: msbuild Re-Framework.csproj
    - name: Test
      run: dotnet test --filter TestCategory="TextBox tests"
      
  Build_Elements.WebTable:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.6
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
    - run: nuget restore Re-Framework.sln
    - name: Restore dependencies
      run: dotnet restore
    - name: Build app for release
      run: msbuild Re-Framework.csproj
    - name: Test
      run: dotnet test --filter TestCategory="WebTable tests"
