name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        nuget: [latest, preview, 4.x, 5.3.1]
        
    name: NuGet@${{ matrix.nuget }} sample
    
    steps:
    - uses: actions/checkout@master
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.6
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: ${{ matrix.nuget }}
    - run: nuget restore Re-Framework.sln
    - name: Restore dependencies
      run: dotnet restore
    - name: Build app for release
      run: msbuild src\Re-Framework.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
