# This is a basic workflow to help you get started with Actions

name: Test Report

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ['.Net']
    types:
      - completed
jobs:
  report:
    runs-on: windows-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: JEST Tests                  # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit  
